export const JOB_GROUP_LIST = [
    { link: '/', title: '전체' },
    { link: '/1', title: '개발' },
    { link: '/2', title: '경영・비즈니스' },
    { link: '/3', title: '마케팅・광고' },
    { link: '/4', title: '디자인' },
    { link: '/5', title: '영업' },
    { link: '/6', title: '고객서비스・리테일' },
    { link: '/7', title: '게임 제작' },
    { link: '/8', title: 'HR' },
    { link: '/9', title: '미디어' },
    { link: '/10', title: '엔지니어링・설계' },
    { link: '/11', title: '금융' },
    { link: '/12', title: '제조・생산' },
    { link: '/13', title: '물류・무역' },
    { link: '/14', title: '의료・제약・바이오' },
    { link: '/15', title: '교육' },
    { link: '/16', title: '법률・법집행기관' },
    { link: '/17', title: '식・음료' },
    { link: '/18', title: '건설・시설' },
    { link: '/19', title: '공공・복지' },
];

export const JOB_CATEGORY_LIST = [
    { id: '1', title: '개발 전체' },
    { id: '2', title: '웹 개발자' },
    { id: '3', title: '서버 개발자' },
    { id: '4', title: '소프트웨어 엔지니어' },
    { id: '5', title: '프론트엔드 개발자' },
    { id: '6', title: '자바 개발자' },
    { id: '7', title: '안드로이드 개발자' },
    { id: '8', title: 'C,C++ 개발자' },
    { id: '9', title: '데이터 엔지니어' },
    { id: '10', title: 'Node.js 개발자' },
    { id: '11', title: 'iOS 개발자' },
    { id: '12', title: '파이썬 개발자' },
    { id: '13', title: 'DevOps / 시스템 관리자' },
    { id: '14', title: '시스템,네트워크 관리자' },
    { id: '15', title: '머신러닝 엔지니어' },
    { id: '16', title: '개발 매니저' },
    { id: '17', title: '기술지원' },
    { id: '18', title: '빅테이터 엔지니어' },
    { id: '19', title: 'QA,테스트 엔지니어' },
    { id: '20', title: '데이터 사이언티스트' },
    { id: '21', title: '보안 엔지니어' },
    { id: '22', title: '프로덕트 매니저' },
    { id: '23', title: '블록체인 플랫폼 엔지니어' },
    { id: '24', title: '임베디드 개발자' },
    { id: '25', title: 'PHP 개발자' },
    { id: '26', title: '하드웨어 엔지니어' },
    { id: '27', title: '.NET 개발자' },
    { id: '28', title: '웹 퍼블리셔' },
    { id: '29', title: 'DBA' },
    { id: '30', title: '크로스플랫폼 앱 개발자' },
    { id: '31', title: '영상,음성 엔지니어' },
    { id: '32', title: '그래픽스 엔지니어' },
    { id: '33', title: 'ERP전문가' },
    { id: '34', title: 'CTO,Chief Technolohhy Officer' },
    { id: '35', title: 'VR 엔지니어' },
    { id: '36', title: 'BI 엔지니어' },
    { id: '37', title: '루비온레일즈 개발자' },
    { id: '38', title: 'CIO,Chief Information Officer' },
];
